apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ntbd2h8ae-nodejs 
  janus-idp.io/tekton: ntbd2h8ae-nodejs
  backstage.io/kubernetes-id: ntbd2h8ae-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ntbd2h8ae-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml