apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ntbd2h8ae-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:577182641f41d5bf7dd78cd353d3c0fded0f8908@sha256:defc7f4524f94d501754a80a6e7ed05edd09c3a785ed347aa49aa7739c779cdf
          name: container-image
